# numpy

* NumPy is a Python library.  
* NumPy is used for working with arrays.  
* NumPy is short for "Numerical Python".
* It also has functions for working in domain of linear algebra, fourier transform, and matrices.   
* It is an open source project and you can use it freely.  

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.   
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.  
Arrays are very frequently used in data science, where speed and resources are very important.   

In [ ]:
# insert the correct method for creating a NumPy array.
arr = np.array([1, 2, 3, 4, 5])

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# NumPy Getting Started

* Installation of NumPy  
If you have Python and PIP already installed on a system, then installation of NumPy is very easy.  
Install it using this command:
C:\Users\Your Name>pip install numpy

    If this command fails, then use a python distribution that already has NumPy installed like, Anaconda, Spyder etc.  

Import Num   Py
Once NumPy is installed, import it in your applications by adding the import keyword:

# Import NumPy
Once NumPy is installed, import it in your applications by adding the import keyword:  
import numpy  
Now NumPy is imported and ready to use.   


In [10]:
# Example
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


# NumPy as np  
NumPy is usually imported under the np alias.  
alias: In Python alias are an alternate name for referring to the same thing.  
Create an alias with the as keyword while importing:  

In [12]:
# Ex
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


# Checking NumPy Version
The version string is stored under __version__ attribute.

In [13]:
# Example
import numpy as np
print(np.__version__)

1.26.4


# NumPy Creating Arrays
NumPy is used to work with arrays. The array object in NumPy is called ndarray.  
We can create a NumPy ndarray object by using the array() function.  

In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
# or 
import numpy as np
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]


# Dimensions in Arrays  
A dimension in arrays is one level of array depth (nested arrays).  
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.  
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.  

These are the most common and basic array  s.

In [16]:
#Create a 0-D array with value 42
import numpy as np
arr = np.array(42)
print(arr)

42


In [17]:
# Create a 1-D array containing the values 1,2,3,4,5:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


* 2-D Arrays  
An array that has 1-D arrays as its elements is called a 2-D array.  
These are often used to represent matrix or 2nd order tensors.  
NumPy has a whole sub module dedicated towards matrix operations called numpy.mat   

In [18]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


* 3-D arrays  
An array that has 2-D arrays (matrices) as its elements is called 3-D array.  
These are often used to represent a 3rd order tensor.  

In [19]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [20]:
# Check how many dimensions the arrays have:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([S
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [21]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# NumPy Array Indexing
Array indexing is the same as accessing an array element.   
You can access an array element by referring to its index number.    
The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.  

In [23]:
# Get the first element from the following array:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[3])

1
4


In [24]:
#Get third and fourth elements from the following array and add them.
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


# Access 2-D Arrays
Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [25]:
# Access the element on the first row, second column:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [26]:
# Access the element on the 2nd row, 5th column:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


# Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.  

In [29]:
# Access the third element of the second array of the first array:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])


6


# Negative Indexing
Use negative indexing to access an array from the end.

In [30]:
# Print the last element from the 2nd dim:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [31]:
# Insert the correct syntax for printing the first item in the array.
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


# Slicing arrays
Slicing in python means taking elements from one given index to another given index.  
We pass slice instead of index like this: [start:end].  
We can also define the step, like this: [start:end:step].  
If we don't pass start its considered 0  
If we don't pass end its considered length of array in that dimension   
If we don't pass step its considered 1   

In [32]:
# Slice elements from index 1 to index 5 from the following array:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

# Slice elements from index 4 to the end of the array:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

# Slice elements from the beginning to index 4 (not included):
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


# Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.  
i - integer  
b - boolean  
u - unsigned integer  
f - float  
c - complex float  
m - timedelta  
M - datetime  
O - object  
S - string  
U - unicode string  
V - fixed chunk of memory for other type ( void )  

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [2]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [3]:
arr = np.array([1, 2, 3, 4,"a",])
print(arr)
print(arr.dtype)

['1' '2' '3' '4' 'a']
<U11


In [13]:
# Make a copy, change the original array, and display both arrays:
# The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [14]:
# view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [5]:
#Shape of an Array
#The shape of an array is the number of elements in each dimension,
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [6]:
# Reshaping arrays
# Reshaping means changing the shape of an array.
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
# Convert the following 1-D array with 12 elements into a 3-D array.
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
# Iterating Arrays
#If we iterate on a 1-D array it will go through each element one by one.
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [8]:
#Iterate on the elements of the following 2-D array:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [9]:
# Iterate on each scalar element of the 2-D array:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [10]:
# Iterating Arrays Using nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [16]:
# Joining NumPy Arrays
# Joining means putting contents of two or more arrays in a single array. 
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [11]:
#filter array
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [12]:
#Split the array in 3 parts:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [17]:
#Find the indexes where the value is 4:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)


(array([3, 5, 6], dtype=int64),)


In [18]:
# Find the indexes where the values are odd:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)
